app:
    min_validity: '72h'
    interval: '6h'
# details about the remote certmaker instance
certmaker:
    host: "http://localhost:8880"
    tls_verify: false # only relevant with https. used to disable tls verification
    apikey: your_key